### ISSUE TITLE
BUG: Enforcing an enforcer that has already exited

### ISSUE THREAD

**Issue by ericrpowers** [aporeto-inc/trireme#321]
While testing trireme, the test was removing PUs when it encountered the following:
```
{"level":"info","ts":1501555386.8419542,"caller":"policy/engine.go:507","msg":"Processing unit removed","ID":"597fe629df7696000117f505","nativeID":"/32344","name":"python-server-0c12212a-ac9c-457c-ae09-a3b2e1c5e09c-0-2"}
{"level":"info","ts":1501555386.8789887,"caller":"policy/engine.go:471","msg":"Processing unit stopped","ID":"597fe608df7696000117f43d","nativeID":"/31074","name":"python-server-0c12212a-ac9c-457c-ae09-a3b2e1c5e09c-0-0"}
[1a2a4263fd4b]:{"level":"fatal","ts":1501555386.9435802,"caller":"remoteenforcer/remoteenforcer_linux.go:377","msg":"Enforcer not inited"}
{"level":"error","ts":1501555386.9456024,"caller":"proxy/enforcerproxy.go:136","msg":"Failed to Enforce remote enforcer","error":"unexpected EOF"}
{"level":"warn","ts":1501555386.945639,"caller":"trireme/trireme.go:303","msg":"Re-initializing enforcers - connection lost"}
{"level":"error","ts":1501555386.9457128,"caller":"processmon/processmon.go:202","msg":"Cannot determine namespace of new container","error":"stat /proc/31846/ns/net: no such file or directory"}
panic: interface conversion: interface {} is nil, not *rpcwrapper.RPCHdl

goroutine 135 [running]:
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer/utils/rpcwrapper.(*RPCWrapper).DestroyRPCClient(0xc4201567e0, 0xc4212b8cc0, 0xc)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer/utils/rpcwrapper/rpc_handle.go:188 +0xac3
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/processmon.(*ProcessMon).KillProcess(0xc42000e070, 0xc4212b8cc0, 0xc)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/processmon/processmon.go:171 +0x2fd
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/supervisor/proxy.(*ProxyInfo).Unsupervise(0xc42019cc40, 0xc4212b8cc0, 0xc, 0xc42040d228, 0xc420261fc0)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/supervisor/proxy/supervisorproxy.go:81 +0xb6
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme.(*trireme).doHandleDelete(0xc4201a3680, 0xc4212b8cc0, 0xc, 0xb43711, 0x4)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/trireme.go:255 +0x3ce
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme.(*trireme).HandlePUEvent(0xc4201a3680, 0xc4212b8cc0, 0xc, 0xb43711, 0x4, 0x0, 0xb55b8f)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/trireme.go:94 +0x146
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.(*dockerMonitor).stopDockerContainer(0xc42028d720, 0xc4212b8cc0, 0x40, 0x3, 0x1)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor/docker.go:514 +0x105
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.(*dockerMonitor).handleDieEvent(0xc42028d720, 0xc421b04380, 0x8eb8f4, 0xc420339450)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor/docker.go:582 +0x42
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.(*dockerMonitor).(github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.handleDieEvent)-fm(0xc421b04380, 0xc42060e750, 0xc421a7cdbc)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor/docker.go:232 +0x34
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.(*dockerMonitor).eventProcessors.func1(0xc42028d720, 0x4)
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor/docker.go:319 +0x15b
created by github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor.(*dockerMonitor).eventProcessors
	/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/monitor/dockermonitor/docker.go:334 +0x54
```

I see two issues here:

1) While removing PUs we hit a fatal due to `s.Enforcer == nil` in `Server.Enforce`, most probably due to us calling `Server.EnforcerExit` in `Server.KillProcess`. I am not entirely sure why these two ran into one another.
2) The panic was due to `rpcHdl` being set to `nil` when trying to convert it at this line:
```
if err := rpcHdl.(*RPCHdl).Client.Close(); err != nil {
```
We do not check if any error comes back from `rpcHdl, _ := r.rpcClientMap.Get(contextID)`. Will make a PR for this.

**Comment by ericrpowers** [comment]
Seems reason 1 is due to a timing of A) a periodic policy update or B) a queued policy update that finally got processed after the Enforcer was removed. We need to have some form of a flag to ignore any subsequent requests right before removing an Enforcer.
